version: '3.8'


volumes:
  pgdata:

services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/

  web:
    image: temana/yamdb_test:v1.11.1111
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./media:/app/media

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/django/static:ro
      - ./media:/var/www/django/media:ro
    ports:
      - "8080:80"
    depends_on:
      - web
